name: first_github_workflow

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  mvn_compile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: compile
      run: mvn clean package
    - uses: actions/upload-artifact@v3
      with:
        name: verademo.war
        path: target/verademo.war
        