name: upload_and_scan

on: 
  push:
    branches: [ main ]

jobs:
  mvn_compile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: compile
      run: mvn clean package
    - uses: actions/upload-artifact@v4
      with:
        name: verademo.war
        path: target/verademo.war
  
  static_analysis:
    runs-on: ubuntu-latest
    needs: mvn_compile
    steps:
        - name: get artifact
          uses: actions/download-artifact@v4
          with:
            name: verademo.war
            path: .
        - name: Veracode Upload And Scan
          uses: veracode/veracode-uploadandscan-action@0.2.6
          with:
            appname: 'VeraDemo_github'
            createprofile: true
            scantimeout: 30
            scanpollinginterval: 30
            filepath: 'verademo.war'
            vid: '${{ secrets.API_ID }}'
            vkey: '${{ secrets.API_KEY }}'

  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository with Veracode SCA
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          SRCCLR_API_URL: ${{ secrets.SRCCLR_API_URL }}
        uses: veracode/veracode-sca@v2.1.11
        with:
          create-issues: true